// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { Capacitor } from '@capacitor/core';

const SUPABASE_URL = "https://sdfihcbjesuxbgftmuoo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNkZmloY2JqZXN1eGJnZnRtdW9vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwOTgzMTksImV4cCI6MjA2NjY3NDMxOX0._Vpl-rocpY2AOPqF8vFAN5GmMYVPlFK51sT0vHc-eoc";

// Custom storage adapter for mobile platforms
const createCustomStorage = () => {
  if (Capacitor.isNativePlatform()) {
    // For native mobile platforms, use a custom storage implementation
    return {
      getItem: async (key: string) => {
        try {
          return window.localStorage.getItem(key);
        } catch (error) {
          console.warn('localStorage not available, falling back to memory storage:', error);
          return null;
        }
      },
      setItem: async (key: string, value: string) => {
        try {
          window.localStorage.setItem(key, value);
        } catch (error) {
          console.warn('localStorage setItem failed:', error);
        }
      },
      removeItem: async (key: string) => {
        try {
          window.localStorage.removeItem(key);
        } catch (error) {
          console.warn('localStorage removeItem failed:', error);
        }
      },
    };
  }

  // For web platform, use default localStorage
  return window.localStorage;
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: createCustomStorage(),
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: false, // Disable for mobile apps
  }
});
