// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sdfihcbjesuxbgftmuoo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNkZmloY2JqZXN1eGJnZnRtdW9vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwOTgzMTksImV4cCI6MjA2NjY3NDMxOX0._Vpl-rocpY2AOPqF8vFAN5GmMYVPlFK51sT0vHc-eoc";

// Custom storage adapter for mobile platforms
const createCustomStorage = () => {
  return window.localStorage;
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: createCustomStorage(),
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: false, // Disable for mobile apps
  }
});
